### ISSUE TITLE
gulp build does not complete

### ISSUE THREAD

**Issue by TuulaP** [jiemakel/arpa-ui#1]
Experimenting with arpa-ui, so I did bower install, npm install, and then when using gulp build, I end up to the below mentioned error. Am I now using this correctly or is there some dependency that could be missing?  I've npm version 2.15.8 and seeing this error both in Centos and Windows7 

> /work/arpas/arpa-ui$ gulp build
> [11:43:02] Requiring external module livescript
> [11:43:03] Using gulpfile /work/arpas/arpa-ui/gulpfile.ls
> [11:43:03] Starting 'build'...
> [11:43:03] Starting 'clean'...
> [11:43:03] Finished 'clean' after 39 ms
> [11:43:03] Starting 'wiredep:styles'...
> [11:43:03] Starting 'wiredep:scripts'...
> [11:43:03] Starting 'templates'...
> [11:43:04] Starting 'styles'...
> [11:43:04] Starting 'scripts'...
> events.js:141
>      throw er; // Unhandled 'error' event
>      ^
> 
> TypeError: must start with number, buffer, array or string
>    at fromObject (buffer.js:156:9)
>    at new Buffer (buffer.js:65:10)
>    at DestroyableTransform._transform (/work/arpas/arpa-ui/node_modules/wiredep/wiredep.js:136:23)
>    at DestroyableTransform.Transform._read (/work/arpas/arpa-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
>    at DestroyableTransform.Transform._write (/work/arpas/arpa-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
>    at doWrite (/work/arpas/arpa-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
>    at writeOrBuffer (/work/arpas/arpa-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
>    at DestroyableTransform.Writable.write (/work/arpas/arpa-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
>    at write (/work/arpas/arpa-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
>    at flow (/work/arpas/arpa-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

Thanks a million for any hint...

**Comment by jiemakel** [comment]
Apparently the functioning of one of the scripts has changed at some point. I fixed it.
